#!/bin/bash
# The logic to stop your application should be put in this script.
#
# Here we do a polite SIGTERM which both the jvm and jetty respond to 
ps -ef | grep zkmongomaps.war | grep -v grep | awk '{ print $2 }' | xargs kill -SIGTERM > /dev/null 2>&1
exit 0
